easy_admin:
    entities:
      Thing:
          class: App\Entity\Thing
          list:
              fields:
                - { property: 'name', type: 'text' }
                - { property: 'wikiLink', type: 'text' }
                - { property: 'inventoryId', type: 'number' }
                - { property: 'description', type: 'text' }
                - { property: 'image', type: 'image', base_path: '%app.path.thing_images%' }
          show:
              fields:
                - { property: 'name', type: 'text' }
                - { property: 'wikiLink', type: 'text' }
                - { property: 'inventoryId', type: 'number' }
                - { property: 'description', type: 'text' }
                - { property: 'image', type: 'image', base_path: '%app.path.thing_images%' }
          form:
              fields:
                - { property: 'name', type: 'text' }
                - { property: 'wikiLink', type: 'text' }
                - { property: 'inventoryId', type: 'number' }
                - { property: 'description', type: 'text' }
                - { property: 'imageFile', type: 'vich_image' }
    site_name: '
    <style>
    .rainbow {
       /* Chrome, Safari, Opera */
      -webkit-animation: rainbow 3s infinite;

      /* Internet Explorer */
      -ms-animation: rainbow 3s infinite;

      /* Standar Syntax */
      animation: rainbow 3s infinite;
    }

    /* Chrome, Safari, Opera */
    @-webkit-keyframes rainbow{
    	20%{color: red;}
    	40%{color: yellow;}
    	60%{color: green;}
    	80%{color: blue;}
    	100%{color: orange;}
    }
    /* Internet Explorer */
    @-ms-keyframes rainbow{
    	20%{color: red;}
    	40%{color: yellow;}
    	60%{color: green;}
    	80%{color: blue;}
    	100%{color: orange;}
    }

    /* Standar Syntax */
    @keyframes rainbow{
    	5%{color: red;}
    	35%{color: yellow;}
    	65%{color: green;}
    	85%{color: blue;}
    	0%{color: orange;}
    }
    </style>
    <span class="rainbow">All the Things</span>'
