vich_uploader:
    db_driver: orm

    mappings:
        thing_images:
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            uri_prefix: /images/things
            upload_destination: '%kernel.project_dir%/public/images/things'
